DROP TABLE IF EXISTS natureza_juridica;

create table natureza_juridica (codigo integer,
descricao varchar(200),
PRIMARY KEY(codigo));

insert into natureza_juridica values (1015, 'Órgão Público do Poder Executivo Federal');
insert into natureza_juridica values (1023, 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal');
insert into natureza_juridica values (1031, 'Órgão Público do Poder Executivo Municipal');
insert into natureza_juridica values (1040, 'Órgão Público do Poder Legislativo Federal');
insert into natureza_juridica values (1058, 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal');
insert into natureza_juridica values (1066, 'Órgão Público do Poder Legislativo Municipal');
insert into natureza_juridica values (1074, 'Órgão Público do Poder Judiciário Federal');
insert into natureza_juridica values (1082, 'Órgão Público do Poder Judiciário Estadual');
insert into natureza_juridica values (1104, 'Autarquia Federal');
insert into natureza_juridica values (1112, 'Autarquia Estadual ou do Distrito Federal');
insert into natureza_juridica values (1120, 'Autarquia Municipal');
insert into natureza_juridica values (1139, 'Fundação Pública de Direito Público Federal');
insert into natureza_juridica values (1147, 'Fundação Pública de Direito Público Estadual ou do Distrito Federal');
insert into natureza_juridica values (1155, 'Fundação Pública de Direito Público Municipal');
insert into natureza_juridica values (1163, 'Órgão Público Autônomo Federal');
insert into natureza_juridica values (1171, 'Órgão Público Autônomo Estadual ou do Distrito Federal');
insert into natureza_juridica values (1180, 'Órgão Público Autônomo Municipal');
insert into natureza_juridica values (1198, 'Comissão Polinacional');
insert into natureza_juridica values (1201, 'Fundo Público');
insert into natureza_juridica values (1210, 'Consórcio Público de Direito Público (Associação Pública)');
insert into natureza_juridica values (1228, 'Consórcio Público de Direito Privado');
insert into natureza_juridica values (1236, 'Estado ou Distrito Federal');
insert into natureza_juridica values (1244, 'Município');
insert into natureza_juridica values (1252, 'Fundação Pública de Direito Privado Federal');
insert into natureza_juridica values (1260, 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal');
insert into natureza_juridica values (1279, 'Fundação Pública de Direito Privado Municipal');
insert into natureza_juridica values (2011, 'Empresa Pública');
insert into natureza_juridica values (2038, 'Sociedade de Economia Mista');
insert into natureza_juridica values (2046, 'Sociedade Anônima Aberta');
insert into natureza_juridica values (2054, 'Sociedade Anônima Fechada');
insert into natureza_juridica values (2062, 'Sociedade Empresária Limitada');
insert into natureza_juridica values (2070, 'Sociedade Empresária em Nome Coletivo');
insert into natureza_juridica values (2089, 'Sociedade Empresária em Comandita Simples');
insert into natureza_juridica values (2097, 'Sociedade Empresária em Comandita por Ações');
insert into natureza_juridica values (2100, '');
insert into natureza_juridica values (2127, 'Sociedade em Conta de Participação');
insert into natureza_juridica values (2135, 'Empresário (Individual)');
insert into natureza_juridica values (2143, 'Cooperativa');
insert into natureza_juridica values (2151, 'Consórcio de Sociedades');
insert into natureza_juridica values (2160, 'Grupo de Sociedades');
insert into natureza_juridica values (2178, 'Estabelecimento, no Brasil, de Sociedade Estrangeira');
insert into natureza_juridica values (2216, 'Empresa Domiciliada no Exterior');
insert into natureza_juridica values (2224, 'Clube/Fundo de Investimento');
insert into natureza_juridica values (2232, 'Sociedade Simples Pura');
insert into natureza_juridica values (2240, 'Sociedade Simples Limitada');
insert into natureza_juridica values (2259, 'Sociedade Simples em Nome Coletivo');
insert into natureza_juridica values (2267, 'Sociedade Simples em Comandita Simples');
insert into natureza_juridica values (2275, 'Empresa Binacional');
insert into natureza_juridica values (2283, 'Consórcio de Empregadores');
insert into natureza_juridica values (2291, 'Consórcio Simples');
insert into natureza_juridica values (2305, 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)');
insert into natureza_juridica values (2313, 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)');
insert into natureza_juridica values (2321, '');
insert into natureza_juridica values (3034, 'Serviço Notarial e Registral (Cartório)');
insert into natureza_juridica values (3069, 'Fundação Privada');
insert into natureza_juridica values (3077, 'Serviço Social Autônomo');
insert into natureza_juridica values (3085, 'Condomínio Edilício');
insert into natureza_juridica values (3107, 'Comissão de Conciliação Prévia');
insert into natureza_juridica values (3115, 'Entidade de Mediação e Arbitragem');
insert into natureza_juridica values (3131, 'Entidade Sindical');
insert into natureza_juridica values (3204, 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras');
insert into natureza_juridica values (3212, 'Fundação ou Associação Domiciliada no Exterior');
insert into natureza_juridica values (3220, 'Organização Religiosa');
insert into natureza_juridica values (3239, 'Comunidade Indígena');
insert into natureza_juridica values (3247, 'Fundo Privado');
insert into natureza_juridica values (3255, 'Órgão de Direção Nacional de Partido Político');
insert into natureza_juridica values (3263, 'Órgão de Direção Regional de Partido Político');
insert into natureza_juridica values (3271, 'Órgão de Direção Local de Partido Político');
insert into natureza_juridica values (3280, 'Comitê Financeiro de Partido Político');
insert into natureza_juridica values (3298, 'Frente Plebiscitária ou Referendária');
insert into natureza_juridica values (3301, 'Organização Social (OS)');
insert into natureza_juridica values (3999, 'Associação Privada');
insert into natureza_juridica values (4014, 'Empresa Individual Imobiliária');
insert into natureza_juridica values (4090, 'Candidato a Cargo Político Eletivo');
insert into natureza_juridica values (4120, 'Produtor Rural (Pessoa Física)');
insert into natureza_juridica values (5010, 'Organização Internacional');
insert into natureza_juridica values (5029, 'Representação Diplomática Estrangeira');
insert into natureza_juridica values (5037, 'Outras Instituições Extraterritoriais');
